# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createroom.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createroom(object):
    def setupUi(self, createroom):
        createroom.setObjectName("createroom")
        createroom.resize(314, 189)
        self.label = QtWidgets.QLabel(createroom)
        self.label.setGeometry(QtCore.QRect(60, 50, 81, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(createroom)
        self.pushButton.setGeometry(QtCore.QRect(110, 130, 91, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(createroom)
        self.lineEdit.setGeometry(QtCore.QRect(160, 50, 113, 31))
        self.lineEdit.setObjectName("lineEdit")

        self.retranslateUi(createroom)
        QtCore.QMetaObject.connectSlotsByName(createroom)

    def retranslateUi(self, createroom):
        _translate = QtCore.QCoreApplication.translate
        createroom.setWindowTitle(_translate("createroom", "Form"))
        self.label.setText(_translate("createroom", "房间名"))
        self.pushButton.setText(_translate("createroom", "OK"))
