# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register(object):
    def setupUi(self, register_2):
        register_2.setObjectName("register_2")
        register_2.resize(709, 468)
        self.label = QtWidgets.QLabel(register_2)
        self.label.setGeometry(QtCore.QRect(0, 0, 701, 461))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../main/login_bg.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(register_2)
        self.label_2.setGeometry(QtCore.QRect(290, 0, 411, 461))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../bgs/7.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(register_2)
        self.label_4.setGeometry(QtCore.QRect(50, 210, 31, 31))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap(":/logsure.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(register_2)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 310, 61, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 15px;\n"
"    font: \"站酷高端黑\";\n"
"    background:#008B8B;\n"
"    border:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#00CED1;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#00CED1;\n"
"}")
        self.pushButton_4.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_3 = QtWidgets.QLabel(register_2)
        self.label_3.setGeometry(QtCore.QRect(50, 140, 31, 31))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/user.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(register_2)
        self.pushButton_3.setGeometry(QtCore.QRect(70, 310, 101, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 15px;\n"
"    font: \"站酷高端黑\";\n"
"    background:#008B8B;\n"
"    border:15px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#00CED1;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#00CED1;\n"
"}")
        self.pushButton_3.setIconSize(QtCore.QSize(32, 32))
        self.pushButton_3.setCheckable(False)
        self.pushButton_3.setAutoRepeat(False)
        self.pushButton_3.setAutoExclusive(False)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton = QtWidgets.QPushButton(register_2)
        self.pushButton.setGeometry(QtCore.QRect(670, 20, 16, 16))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 7px;\n"
"    font-family:微软雅黑;\n"
"    background:#FF0000;\n"
"    border:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#BC1717;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#BC1717;\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(register_2)
        self.pushButton_2.setGeometry(QtCore.QRect(640, 20, 16, 16))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"    color:White;\n"
"    border-radius: 7px;\n"
"    font-family:微软雅黑;\n"
"    background:#C0C0C0;\n"
"    border:7px;\n"
"}\n"
"QPushButton:hover{\n"
"    background:#A8A8A8;\n"
"}\n"
"QPushButton:pressed{\n"
"    background:#A8A8A8;\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_10 = QtWidgets.QLabel(register_2)
        self.label_10.setGeometry(QtCore.QRect(100, 210, 141, 16))
        self.label_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(register_2)
        self.label_11.setGeometry(QtCore.QRect(100, 260, 141, 16))
        self.label_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(register_2)
        self.label_12.setGeometry(QtCore.QRect(100, 160, 141, 16))
        self.label_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.label_12.setText("")
        self.label_12.setObjectName("label_12")
        self.lineEdit = QtWidgets.QLineEdit(register_2)
        self.lineEdit.setGeometry(QtCore.QRect(100, 140, 141, 31))
        self.lineEdit.setAutoFillBackground(False)
        self.lineEdit.setStyleSheet("")
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setFrame(False)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(register_2)
        self.lineEdit_2.setGeometry(QtCore.QRect(100, 190, 141, 31))
        self.lineEdit_2.setAutoFillBackground(False)
        self.lineEdit_2.setInputMask("")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(register_2)
        self.lineEdit_3.setGeometry(QtCore.QRect(100, 240, 141, 31))
        self.lineEdit_3.setAutoFillBackground(False)
        self.lineEdit_3.setInputMask("")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setFrame(False)
        self.lineEdit_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.pushButton_4.raise_()
        self.label_3.raise_()
        self.pushButton_3.raise_()
        self.pushButton.raise_()
        self.pushButton_2.raise_()
        self.label_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()

        self.retranslateUi(register_2)
        QtCore.QMetaObject.connectSlotsByName(register_2)

    def retranslateUi(self, register_2):
        _translate = QtCore.QCoreApplication.translate
        register_2.setWindowTitle(_translate("register_2", "Form"))
        self.pushButton_4.setText(_translate("register_2", "登录"))
        self.pushButton_3.setText(_translate("register_2", "注册"))
        self.lineEdit.setPlaceholderText(_translate("register_2", "账号"))
        self.lineEdit_2.setPlaceholderText(_translate("register_2", "密码"))
        self.lineEdit_3.setPlaceholderText(_translate("register_2", "再输入一次密码"))
import login_rc
